hoopler/urls.py
from django.conf.urls import url, patterns, include
from django.contrib import admin
from core.views import RosterView, DashboardView

urlpatterns = patterns(
    '',
    url(r'^roster/$', RosterView.as_view(), name='roster'),

    url(r'^$', DashboardView.as_view(), name='dashboard'),

    url(r'^admin/', include(admin.site.urls)),
)

core/models.py
import moneyed
from djmoney.models.fields import MoneyField
from moneyed import Money
from django.db import models
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    type_choices = (
        ('SU', 'Superuser'), ('I', 'Instructor'), ('S', 'Student'))
    user_type = models.CharField(
        max_length=2, choices=type_choices,  default='S')


class Instructor(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE)


class Period(models.Model):
    name = models.CharField(max_length=40)
    instructor = models.ForeignKey(Instructor)
    payscale = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')
    average_adjust = models.IntegerField()

    def class_average(self):
        if self.student_set.count() == 0:
            return 0
        else:
            cash = self.student_set.values_list('cash', flat=True)
            return Money(
                sum(cash) / len(cash) + (self.average_adjust or 0), 'USD')

    def pay_students(self):
        for student in self.student_set.all():
            student.cash += self.payscale
            student.save()

    def richest(self):
        return self.students.all().order_by('-cash').first()

    def total_bonuses(self):
        return Money(
            sum(self.periodbonus_set.values_list('amount', flat=True)), 'USD')


class Student(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    period = models.ForeignKey(Period)
    cash = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')

    def well_behaved(self):
        if self.behavior_set.last() and self.behavior_set.last().well_behaved:
            return True
        else:
            return False

# Transaction Models
class BaseTransaction(models.Model):
    date = models.DateField()
    reason = models.TextField()
    sender = models.ForeignKey(MyUser)
    amount = MoneyField(
        max_digits=10, decimal_places=2, default_currency='USD')

    class Meta:
        abstract = True

class Transaction(BaseTransaction):
    recipient = models.ForeignKey(Student)

class StudentBonus(BaseTransaction):
    student = models.ForeignKey(Student)

    def save(self, *args, **kwargs):
        self.student.cash -= self.amount
        self.student.save()
        super(StudentBonus, self).save(*args, **kwargs)

class PeriodBonus(BaseTransaction):
    period = models.ForeignKey(Period)

    def distribute_bonus(self):
        portion = self.amount / self.period.students.count()
        for student in self.period.students:
            student.cash += portion
            student.save()


class Behavior(models.Model):
    student = models.ForeignKey(Student)
    date = models.DateField()
    well_behaved = models.BooleanField()
    current_balance = MoneyField(
        max_digits=10, decimal_places=2, default_currency='USD')


class Job(models.Model):
    name = models.CharField(max_length=80)
    student = models.ForeignKey(Student)
    boss = models.ForeignKey(MyUser, related_name='employees')
    payscale = MoneyField(
        max_digits=10, decimal_places=2, default_currency='USD')

store/models.py
import moneyed
from djmoney.models.fields import MoneyField
from django.db import models
from core.models import Student

class StoreItem(models.Model):
    name = models.CharField(max_length=20)
    price = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')
    stock = models.IntegerField(null=True, blank=True)

    def buy(self, student):
        if student.cash >= self.price and (self.stock > 0 or self.stock == None):
            self.purchase_set.create(purchaser=student)
            student.cash -= self.price
            student.save()
            if self.stock:
                self.stock -= 1
                self.save()
        else:
            return False

class Purchase(models.Model):
    purchaser = models.ForeignKey(Student)
    item = models.ForeignKey(StoreItem)

core/views.py
from django.shortcuts import render
from django.views.generic import (
    View, TemplateView, ListView, DetailView, FormView, UpdateView
)
from models import *

class DashboardView(TemplateView):
    template_name = 'core/dashboard.html'

class RosterView(TemplateView):
    template_name = 'core/roster.html'

    def get_context_data(self, **kwargs):
        context = super(RosterView, self).get_context_data(**kwargs)
        context['periods'] = self.request.user.instructor.period_set.all()
        return context

core/templates/core/layout.html
{% load bootstrap3 %}

{% bootstrap_css %}

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-left">
      <li><a href="#">{% bootstrap_icon 'home' %}</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="#">Roster</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="#">Jobs</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="#">Awards</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="#">Transactions</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="#">Loans</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="#">Rights</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="#">Store</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="#">Rankings</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">{% bootstrap_icon 'log-out' %}</a></li>
    </ul>
  </div>
</nav>

{% block content %}{% endblock %}

core/templates/core/roster.html
{% extends 'core/layout.html' %}
{% load bootstrap3 %}

{% bootstrap_css %}

{% block content %}
  {% for period in periods %}
    <div id={{period.name}}>
      <span>{{ period.name }}</span>
      <span>Payscale: {{ period.payscale }}</span>
      <span>Total Students: {{ period.student_set.count }}</span>
      <span>Class Average: {{ period.class_average }}</span>
      <span>Class Bonus Total: {{ period.total_bonuses }}</span>
    </div>

    <table id='{{ period.name }}-students' class='table table-striped'>
      <thead>
        <th>Student</th>
        <th>Cash</th>
        <th>Recent Behavior</th>
        <th>Jobs</th>
        <th>Rights</th>
        <th></th>
      </thead>
      <tbody>
        {% for student in period.student_set.all %}
          <tr id='student-{{ student.pk }}'>
            <td>{{ student.user.get_full_name }}</td>
            <td>{{ student.cash }}</td>
            <td>
              {% if student.well_behaved %}
                {% bootstrap_icon 'certificate' %}
              {% endif %}
            </td>
            <td>
              <ul>
                {% for j in student.job_set.all %}
                  <li>{{ j.name }}</li>
                {% endfor %}
              </ul>
            </td>
            <td>
              <ul>
                {% for r in student.right_set.all %}
                  <li>{{ r.name }}</li>
                {% endfor %}
              </ul>
            </td>
          </tr>
        {% endfor %}
    </table>
  {% endfor %}
{% endblock %}